# Generated by Django 2.1.5 on 2019-02-07 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0002_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(upload_to='static/images/members'),
        ),
    ]
