# Generated by Django 2.1.5 on 2019-02-09 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0003_auto_20190207_0030'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Indicator Item',
                'verbose_name_plural': 'Indicator Items',
            },
        ),
        migrations.CreateModel(
            name='IndicatorVision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Indicator Vision',
                'verbose_name_plural': 'Indicator Visions',
            },
        ),
        migrations.CreateModel(
            name='MemberHolidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Member Holidays',
                'verbose_name_plural': 'Member Holidays',
            },
        ),
        migrations.CreateModel(
            name='MemberOneOneMeeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_meeting_date', models.DateField()),
                ('last_meeting_manager', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Member One One Meeting',
                'verbose_name_plural': 'Member One One Meetings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('client', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectIndicatorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicator_projects', to='agile_vision_app.IndicatorItem')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='agile_vision_app.Project')),
            ],
            options={
                'verbose_name': 'Project Indicator Item',
                'verbose_name_plural': 'Project Indicator Items',
            },
        ),
        migrations.CreateModel(
            name='ProjectMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Project Member',
                'verbose_name_plural': 'Project Members',
            },
        ),
        migrations.CreateModel(
            name='ProjectTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_teams', to='agile_vision_app.Project')),
            ],
            options={
                'verbose_name': 'Project Team',
                'verbose_name_plural': 'Project Teams',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('development_time', models.IntegerField()),
                ('validation_time', models.IntegerField()),
                ('blocking_time', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Task',
                'verbose_name_plural': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='TaskComplexity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('weight', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Task Complexity',
                'verbose_name_plural': 'Task Complexities',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('photo', models.ImageField(upload_to='static/images/teams')),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.AddField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(max_length=1000),
        ),
        migrations.AddField(
            model_name='task',
            name='complexity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexity_tasks', to='agile_vision_app.TaskComplexity'),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_tasks', to='agile_vision_app.Project'),
        ),
        migrations.AddField(
            model_name='projectteam',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_projects', to='agile_vision_app.Team'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_projects', to='agile_vision_app.Member'),
        ),
        migrations.AddField(
            model_name='projectmember',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_members', to='agile_vision_app.Project'),
        ),
        migrations.AddField(
            model_name='memberoneonemeeting',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='one_one_meetings', to='agile_vision_app.Member'),
        ),
        migrations.AddField(
            model_name='memberholidays',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='agile_vision_app.Member'),
        ),
        migrations.AddField(
            model_name='indicatoritem',
            name='indicator_vision_currently_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_month_indicator_items', to='agile_vision_app.IndicatorVision'),
        ),
        migrations.AddField(
            model_name='indicatoritem',
            name='indicator_vision_next_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_month_indicator_items', to='agile_vision_app.IndicatorVision'),
        ),
    ]
