# Generated by Django 2.1.5 on 2019-02-09 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0004_auto_20190209_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indicatoritem',
            name='indicator_vision_currently_month',
        ),
        migrations.RemoveField(
            model_name='indicatoritem',
            name='indicator_vision_next_month',
        ),
        migrations.RemoveField(
            model_name='projectindicatoritem',
            name='indicator_item',
        ),
        migrations.AddField(
            model_name='projectindicatoritem',
            name='description',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectindicatoritem',
            name='indicator_vision_currently_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_month_indicator_items', to='agile_vision_app.IndicatorVision'),
        ),
        migrations.AddField(
            model_name='projectindicatoritem',
            name='indicator_vision_next_month',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_month_indicator_items', to='agile_vision_app.IndicatorVision'),
        ),
        migrations.DeleteModel(
            name='IndicatorItem',
        ),
    ]
