# Generated by Django 2.1.5 on 2019-02-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0005_auto_20190209_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Indicator Type',
                'verbose_name_plural': 'Indicator Types',
            },
        ),
        migrations.RemoveField(
            model_name='projectindicatoritem',
            name='description',
        ),
        migrations.AddField(
            model_name='projectindicatoritem',
            name='indicator_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='agile_vision_app.IndicatorType'),
        ),
    ]
