# Generated by Django 2.1.5 on 2019-02-10 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0007_project_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(null=True, related_name='projects', to='agile_vision_app.ProjectMember'),
        ),
    ]
