# Generated by Django 2.1.5 on 2019-02-10 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0008_auto_20190210_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, to='agile_vision_app.Member'),
        ),
    ]
