# Generated by Django 2.1.5 on 2019-02-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0010_remove_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='projectmember',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='projects', to='agile_vision_app.Member'),
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
