# Generated by Django 2.1.5 on 2019-02-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0014_auto_20190211_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberoneonemeeting',
            name='member',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_holiday_period',
        ),
        migrations.AddField(
            model_name='member',
            name='last_one_one_meeting_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='last_one_one_meeting_manager',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='next_holidays_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='next_holidays_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='description',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='mentor',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(null=True, upload_to='static/images/members'),
        ),
        migrations.DeleteModel(
            name='HolidaysPeriod',
        ),
        migrations.DeleteModel(
            name='MemberOneOneMeeting',
        ),
    ]
