# Generated by Django 2.1.5 on 2019-02-11 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0015_auto_20190211_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='agile_vision_app.IndicatorType')),
                ('indicator_vision_currently_month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='currently_month_indicator_items', to='agile_vision_app.IndicatorVision')),
                ('indicator_vision_next_month', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_month_indicator_items', to='agile_vision_app.IndicatorVision')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='agile_vision_app.Project')),
            ],
            options={
                'verbose_name': 'Project Indicator Item',
                'verbose_name_plural': 'Project Indicator Items',
            },
        ),
        migrations.RemoveField(
            model_name='projectindicatoritem',
            name='indicator_type',
        ),
        migrations.RemoveField(
            model_name='projectindicatoritem',
            name='indicator_vision_currently_month',
        ),
        migrations.RemoveField(
            model_name='projectindicatoritem',
            name='indicator_vision_next_month',
        ),
        migrations.RemoveField(
            model_name='projectindicatoritem',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectIndicatorItem',
        ),
    ]
