# Generated by Django 2.1.5 on 2019-02-20 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0022_auto_20190220_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='delivery_date',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='blocking_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='complexity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complexity_tasks', to='agile_vision_app.TaskComplexity'),
        ),
        migrations.AlterField(
            model_name='task',
            name='development_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='validation_time',
            field=models.IntegerField(null=True),
        ),
    ]
