# Generated by Django 2.1.5 on 2019-02-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0023_auto_20190220_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='blocking_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='development_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='validation_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
