# Generated by Django 2.1.7 on 2019-02-20 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0024_auto_20190220_0127'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskLabel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('color', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Task Label',
                'verbose_name_plural': 'Task Labels',
            },
        ),
    ]
