# Generated by Django 2.1.7 on 2019-02-20 02:09

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0025_tasklabel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklabel',
            name='color',
            field=colorfield.fields.ColorField(max_length=18, null=True),
        ),
    ]
