# Generated by Django 2.1.7 on 2019-02-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agile_vision_app', '0026_auto_20190220_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='agile_vision_app.TaskLabel'),
        ),
    ]
